server:
  port: 9999
  servlet:
    context-path: /es_springboot03

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucene
    username: root
    password: 123456

  data:
    elasticsearch:
      cluster-nodes: 192.168.80.146:9300,192.168.80.145:9300
      cluster-name: es666
  freemarker:
    suffix: .ftl
    prefix: /
mybatis:
  mapper-locations: classpath:com/cps/www/dao/impl/*.xml
  type-aliases-package: com.cps.www.entity


